import { router } from 'expo-router';
import { useEffect,useState } from 'react';
import { Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { apiUrl } from '../lib/api';
import { authHeaders,authenticatedTenantHeaders,getTenant,saveTenant } from '../lib/session';

type Member={identityId:string;email:string;role:string;createdAt:string;deactivatedAt?:string|null};
type Invitation={id:string;email:string;role:string;expiresAt:string;acceptedAt?:string|null;revokedAt?:string|null};

export default function Membros(){
  const[members,setMembers]=useState<Member[]>([]),[invitations,setInvitations]=useState<Invitation[]>([]),[canManage,setCanManage]=useState(false);
  const[email,setEmail]=useState(''),[role,setRole]=useState('manager'),[inviteCode,setInviteCode]=useState(''),[generatedCode,setGeneratedCode]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{void loadManagement();},[]);
  async function loadManagement(){
    const tenant=await getTenant();if(!tenant){setCanManage(false);return;}
    const h=await authenticatedTenantHeaders();const [m,i]=await Promise.all([fetch(apiUrl('/company/members'),{headers:h}),fetch(apiUrl('/company/members/invitations'),{headers:h})]);
    if(m.ok&&i.ok){setCanManage(true);setMembers(await m.json());setInvitations(await i.json());}else setCanManage(false);
  }
  async function createInvite(){setBusy(true);try{const h=await authenticatedTenantHeaders();const r=await fetch(apiUrl('/company/members/invitations'),{method:'POST',headers:{...h,'content-type':'application/json'},body:JSON.stringify({email,role})});const x=await r.json().catch(()=>({}));if(!r.ok){setGeneratedCode('');setMessage('Não foi possível gerar o convite.');return;}setGeneratedCode(x.inviteCode);setMessage(`Convite criado para ${x.email}.`);await loadManagement();}finally{setBusy(false);}}
  async function acceptInvite(){setBusy(true);try{const h=await authHeaders();const r=await fetch(apiUrl('/company/members/invitations/accept'),{method:'POST',headers:{...h,'content-type':'application/json'},body:JSON.stringify({inviteCode:inviteCode.trim()})});const x=await r.json().catch(()=>({}));if(!r.ok){setMessage(x?.message==='invitation_email_mismatch'?'Este convite pertence a outro e-mail.':x?.message==='invitation_existing_membership_role_change_forbidden'?'Você já participa desta empresa com outro papel. Alterações de papel precisam seguir o fluxo de gestão da empresa.':'Convite inválido, expirado ou já utilizado.');return;}setInviteCode('');await saveTenant(x.tenantId);setMessage(`Convite aceito como ${x.role}.`);if(['owner','admin','manager'].includes(x.role))router.replace('/empresa-inicio');}finally{setBusy(false);}}
  async function revoke(id:string){setBusy(true);try{const h=await authenticatedTenantHeaders();const r=await fetch(apiUrl(`/company/members/invitations/${id}/revoke`),{method:'POST',headers:h});setMessage(r.ok?'Convite revogado.':'Não foi possível revogar.');if(r.ok){setGeneratedCode('');await loadManagement();}}finally{setBusy(false);}}
  return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={s.content}><Text style={s.title}>Membros da empresa</Text><Text style={s.heading}>Aceitar convite</Text><TextInput style={s.input} autoCapitalize="none" placeholder="Cole o código do convite" value={inviteCode} onChangeText={setInviteCode}/><Pressable disabled={busy||!inviteCode.trim()} style={s.button} onPress={()=>void acceptInvite()}><Text style={s.bold}>Aceitar convite</Text></Pressable>{canManage?<><Text style={s.heading}>Convidar membro</Text><TextInput style={s.input} autoCapitalize="none" keyboardType="email-address" placeholder="E-mail" value={email} onChangeText={setEmail}/><View style={s.row}>{['manager','admin','owner'].map(r=><Pressable key={r} style={[s.role,role===r&&s.selected]} onPress={()=>setRole(r)}><Text style={s.bold}>{r}</Text></Pressable>)}</View><Pressable disabled={busy||!email.includes('@')} style={s.button} onPress={()=>void createInvite()}><Text style={s.bold}>Gerar convite</Text></Pressable>{generatedCode?<View style={s.code}><Text style={s.bold}>Código do convite</Text><Text selectable>{generatedCode}</Text><Text>Compartilhe somente com a pessoa do e-mail informado. O código expira.</Text><Pressable style={s.smallButton} onPress={()=>setGeneratedCode('')}><Text style={s.bold}>Ocultar código</Text></Pressable></View>:null}<Text style={s.heading}>Membros</Text>{members.map(m=><View key={m.identityId} style={s.card}><Text style={s.bold}>{m.email}</Text><Text>Papel: {m.role}</Text><Text>{m.deactivatedAt?'Conta desativada':'Ativo'}</Text></View>)}<Text style={s.heading}>Convites</Text>{invitations.filter(i=>!i.acceptedAt&&!i.revokedAt).map(i=><View key={i.id} style={s.card}><Text style={s.bold}>{i.email}</Text><Text>Papel: {i.role}</Text><Text>Expira: {new Date(i.expiresAt).toLocaleString()}</Text><Pressable style={s.smallButton} onPress={()=>void revoke(i.id)}><Text style={s.bold}>Revogar</Text></Pressable></View>)}</>:<Text>Se você é proprietário de uma empresa, selecione o workspace da empresa para gerenciar membros. Você ainda pode aceitar um convite acima.</Text>}{message?<Text style={s.message}>{message}</Text>:null}</ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#fff'},content:{padding:24,gap:12},title:{fontSize:30,fontWeight:'800'},heading:{fontSize:21,fontWeight:'800',marginTop:8},input:{borderWidth:1,borderRadius:12,padding:14},button:{borderWidth:2,borderRadius:12,padding:14,alignItems:'center'},smallButton:{borderWidth:1,borderRadius:10,padding:9,alignItems:'center'},row:{flexDirection:'row',gap:8,flexWrap:'wrap'},role:{borderWidth:1,borderRadius:10,paddingVertical:9,paddingHorizontal:14},selected:{borderWidth:3},card:{borderWidth:1,borderRadius:12,padding:14,gap:4},code:{borderWidth:1,borderRadius:12,padding:14,gap:8},bold:{fontWeight:'800'},message:{fontWeight:'700'}});
