import { router } from 'expo-router';
import { useEffect,useState } from 'react';
import { Pressable,SafeAreaView,StyleSheet,Text,TextInput,View } from 'react-native';
import { ProfessionalNav } from '../components/ProfessionalNav';
import { authHeaders,clearSession,clearTenant } from '../lib/session';
import { apiUrl } from '../lib/api';
type Passport={displayName:string;completedWorkCount:number;averageRating:number|null;ratingCount:number;verifiedHistory:{id:string;tenantId:string;title:string;location?:string}[]};
export default function Perfil(){const[p,setP]=useState<Passport|null>(null),[displayName,setDisplayName]=useState(''),[homeCity,setHomeCity]=useState(''),[primaryRole,setPrimaryRole]=useState(''),[message,setMessage]=useState('');useEffect(()=>{void load();},[]);async function load(){const h=await authHeaders();const [profile,passport]=await Promise.all([fetch(apiUrl('/professional-profile'),{headers:h}),fetch(apiUrl('/work-passport/mine'),{headers:h})]);if(profile.ok){const x=await profile.json();if(x){setDisplayName(x.displayName??'');setHomeCity(x.homeCity??'');setPrimaryRole(x.primaryRole??'');}}if(passport.ok)setP(await passport.json());}async function save(){const h=await authHeaders();const r=await fetch(apiUrl('/professional-profile'),{method:'PUT',headers:{...h,'content-type':'application/json'},body:JSON.stringify({displayName,homeCity,primaryRole})});setMessage(r.ok?'Perfil salvo.':'Não foi possível salvar.');if(r.ok)await load();}async function signout(){const h=await authHeaders();try{await fetch(apiUrl('/auth/signout'),{method:'POST',headers:h});}finally{await Promise.all([clearSession(),clearTenant()]);router.replace('/');}}return <SafeAreaView style={s.screen}><View style={s.content}><ProfessionalNav/><Text style={s.title}>Seu perfil</Text><TextInput style={s.input} placeholder="Seu nome" value={displayName} onChangeText={setDisplayName}/><TextInput style={s.input} placeholder="Função principal (ex.: Bartender)" value={primaryRole} onChangeText={setPrimaryRole}/><TextInput style={s.input} placeholder="Cidade" value={homeCity} onChangeText={setHomeCity}/><Pressable style={s.button} onPress={()=>void save()}><Text style={s.bold}>Salvar perfil</Text></Pressable><Text>{message}</Text><Text style={s.heading}>Work Passport</Text><Text>{p?.completedWorkCount??0} trabalhos verificados</Text><Text>{p?.averageRating!=null?p.averageRating.toFixed(1)+' ★ ('+p.ratingCount+')':'Ainda sem avaliações'}</Text>{p?.verifiedHistory.map(h=><View key={h.id} style={s.card}><Text style={s.bold}>{h.title}</Text><Text>{h.location??'Local não informado'}</Text></View>)}<Pressable style={s.signout} onPress={()=>void signout()}><Text style={s.bold}>Sair da conta</Text></Pressable></View></SafeAreaView>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#fff'},content:{padding:24,gap:12},title:{fontSize:30,fontWeight:'800'},heading:{fontSize:22,fontWeight:'800',marginTop:8},input:{borderWidth:1,borderRadius:12,padding:14},button:{borderWidth:1,borderRadius:12,padding:15,alignItems:'center'},signout:{padding:15,alignItems:'center',marginTop:10},bold:{fontWeight:'800'},card:{borderWidth:1,borderRadius:12,padding:14,gap:5}});
