import { router } from 'expo-router';
import { useEffect,useState } from 'react';
import { Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { apiUrl } from '../lib/api';
import { authHeaders,clearSession,clearTenant } from '../lib/session';

type PrivacyRequest={id:string;requestType:string;requestDetails?:string|null;status:string;resolutionCode?:string|null;createdAt:string;completedAt?:string|null};
const requestLabels:Record<string,string>={correction:'Solicitar correção',erasure:'Solicitar eliminação',restriction:'Solicitar restrição',objection:'Registrar oposição',consent_withdrawal:'Revogar consentimento',automated_decision_review:'Solicitar revisão de decisão automatizada',sharing_information:'Pedir informações de compartilhamento',portability:'Solicitar portabilidade, quando aplicável'};
const detailsRequired=new Set(['correction','restriction','objection','automated_decision_review']);

export default function Privacidade(){
  const[requests,setRequests]=useState<PrivacyRequest[]>([]),[message,setMessage]=useState(''),[details,setDetails]=useState(''),[exportText,setExportText]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{void load();return()=>setExportText('');},[]);
  async function load(){const h=await authHeaders();const r=await fetch(apiUrl('/privacy/requests'),{headers:h});if(r.ok)setRequests(await r.json());}
  async function createRequest(requestType:string){if(detailsRequired.has(requestType)&&!details.trim()){setMessage('Descreva brevemente o que precisa ser corrigido, restringido, contestado ou revisado.');return;}setBusy(true);try{const h=await authHeaders();const r=await fetch(apiUrl('/privacy/requests'),{method:'POST',headers:{...h,'content-type':'application/json'},body:JSON.stringify({requestType,details:details.trim()||undefined})});const body=await r.json().catch(()=>({}));if(r.ok){setDetails('');setMessage(`Pedido registrado: ${body.requestId}`);await load();}else setMessage(body?.message==='privacy_request_details_required'?'Inclua os detalhes necessários para este pedido.':body?.message==='privacy_request_details_too_long'?'O texto do pedido precisa ter até 2.000 caracteres.':'Não foi possível registrar o pedido.');}finally{setBusy(false);}}
  async function exportData(){setBusy(true);try{const h=await authHeaders();const r=await fetch(apiUrl('/privacy/export'),{headers:h});if(r.ok){const x=await r.json();setExportText(JSON.stringify(x,null,2));setMessage(`Cópia gerada. Pedido: ${x.requestId}`);await load();}else setMessage('Não foi possível gerar a cópia dos dados.');}finally{setBusy(false);}}
  function confirmDeactivate(){Alert.alert('Desativar conta','A desativação encerra a sessão e pode ser bloqueada se houver trabalho ativo, valor pendente ou se você for o único proprietário de uma empresa.',[{text:'Cancelar',style:'cancel'},{text:'Desativar',style:'destructive',onPress:()=>void deactivate()}]);}
  async function deactivate(){setBusy(true);try{const h=await authHeaders();const r=await fetch(apiUrl('/privacy/deactivate'),{method:'POST',headers:h});const body=await r.json().catch(()=>({}));if(!r.ok){setMessage(body?.message==='account_deactivation_active_assignment'?'Não é possível desativar com trabalho ativo.':body?.message==='account_deactivation_unsettled_earnings'?'Não é possível desativar enquanto houver ganhos pendentes.':body?.message==='account_deactivation_sole_tenant_owner'?'Antes de desativar, defina outro proprietário para a empresa.':'Não foi possível desativar a conta.');await load();return;}setExportText('');await Promise.all([clearSession(),clearTenant()]);router.replace('/');}finally{setBusy(false);}}
  return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={s.content}><Text style={s.title}>Privacidade e dados</Text><Text>Você pode acessar seus dados, registrar pedidos e acompanhar o estado de cada solicitação.</Text><View style={s.notice}><Text style={s.bold}>Como usamos seus dados</Text><Text>Usamos dados de conta, perfil, disponibilidade, trabalhos, mensagens, reputação, segurança e informações financeiras necessárias para operar o serviço.</Text><Text>Localização precisa não é rastreada em segundo plano. Quando usada no check-in/out, é episódica e sua precisão é removida conforme a política de retenção, salvo conservação justificada.</Text><Text>Dados são mantidos apenas pelo tempo necessário à finalidade e podem ser compartilhados somente quando necessários para a operação, infraestrutura, pagamentos, verificação ou obrigação aplicável.</Text><Text>Matching e ranking podem usar sinais automatizados, mas efeitos materiais críticos não devem resultar em punição automática sem possibilidade de revisão humana.</Text></View><Pressable disabled={busy} style={s.primary} onPress={()=>void exportData()}><Text style={s.bold}>Gerar cópia dos meus dados</Text></Pressable><Text style={s.heading}>Registrar outro pedido</Text><TextInput style={s.input} multiline maxLength={2000} placeholder="Detalhes do pedido (necessários para correção, restrição, oposição ou revisão)" value={details} onChangeText={setDetails}/>{Object.entries(requestLabels).map(([type,label])=><Pressable disabled={busy} key={type} style={s.button} onPress={()=>void createRequest(type)}><Text style={s.bold}>{label}</Text></Pressable>)}{message?<Text style={s.message}>{message}</Text>:null}{exportText?<View style={s.exportBox}><Text>Esta cópia é exibida somente nesta tela e não é salva pelo aplicativo.</Text><Text selectable>{exportText}</Text><Pressable style={s.button} onPress={()=>setExportText('')}><Text style={s.bold}>Limpar cópia exibida</Text></Pressable></View>:null}<Text style={s.heading}>Meus pedidos</Text>{requests.length===0?<Text>Nenhum pedido registrado.</Text>:requests.map(r=><View key={r.id} style={s.card}><Text style={s.bold}>{r.requestType}</Text><Text>Status: {r.status}</Text>{r.requestDetails?<Text>Detalhes: {r.requestDetails}</Text>:null}<Text selectable>ID: {r.id}</Text><Text>{new Date(r.createdAt).toLocaleString()}</Text>{r.resolutionCode?<Text>Resultado: {r.resolutionCode}</Text>:null}</View>)}<Text style={s.heading}>Conta</Text><Pressable disabled={busy} style={s.danger} onPress={confirmDeactivate}><Text style={s.bold}>Desativar minha conta</Text></Pressable></ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#fff'},content:{padding:24,gap:12},title:{fontSize:30,fontWeight:'800'},heading:{fontSize:22,fontWeight:'800',marginTop:8},input:{borderWidth:1,borderRadius:12,padding:14,minHeight:90,textAlignVertical:'top'},primary:{borderWidth:2,borderRadius:12,padding:15,alignItems:'center'},button:{borderWidth:1,borderRadius:12,padding:14,alignItems:'center'},danger:{borderWidth:1,borderRadius:12,padding:14,alignItems:'center',marginBottom:30},bold:{fontWeight:'800'},message:{fontWeight:'700'},card:{borderWidth:1,borderRadius:12,padding:14,gap:4},notice:{borderWidth:1,borderRadius:12,padding:14,gap:8},exportBox:{borderWidth:1,borderRadius:12,padding:12,maxHeight:360,gap:10}});
