import { Link } from 'expo-router';
import { SafeAreaView,ScrollView,StyleSheet,Text,View } from 'react-native';
import { ProfessionalNav } from '../components/ProfessionalNav';
export default function ProfissionalInicio(){return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={s.content}>
<View style={s.brandRow}><Text style={s.brand}>MLIVRE<Text style={s.purple}>TRABALHO</Text></Text><Text style={s.bell}>♧</Text></View>
<Text style={s.greeting}>Olá, Ana!</Text><Text style={s.subtitle}>Pronta para novos trabalhos?</Text>
<View style={s.stats}><View style={s.stat}><Text style={s.statLabel}>Hoje</Text><Text style={s.statValue}>2</Text><Text style={s.small}>trabalhos</Text></View><View style={s.stat}><Text style={s.statLabel}>Ganhos</Text><Text style={s.statValue}>R$ 120,00</Text></View></View>
<Link href="/trabalhos" style={s.primary}>VER TRABALHOS  →</Link>
<Text style={s.heading}>Próximo trabalho</Text><Link href="/agenda" style={s.card}><Text style={s.cardTitle}>Atendente de Eventos</Text><Text style={s.meta}>◷ Hoje · 14:00 – 20:00</Text><Text style={s.meta}>⌾ Espaço Central · 2,3 km</Text><Text style={s.chevron}>›</Text></Link>
<Text style={s.heading}>Sua disponibilidade</Text><Link href="/disponibilidade" style={s.availability}><Text style={s.green}>●</Text><Text style={s.availText}>Disponível para novos trabalhos</Text><Text style={s.chev}>›</Text></Link>
</ScrollView><ProfessionalNav/></SafeAreaView>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#FFF'},content:{padding:20,gap:9,paddingBottom:24},brandRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},brand:{fontSize:19,fontWeight:'900',color:'#111A35'},purple:{color:'#651FFF'},bell:{fontSize:24,color:'#651FFF'},greeting:{fontSize:25,fontWeight:'900',color:'#111A35',marginTop:5},subtitle:{fontSize:14,color:'#65708A',marginBottom:8},stats:{flexDirection:'row',gap:10},stat:{flex:1,minHeight:88,padding:14,borderWidth:1,borderColor:'#EEF0F5',borderRadius:12,backgroundColor:'#FFF'},statLabel:{fontSize:13,color:'#111A35'},statValue:{fontSize:22,fontWeight:'900',color:'#111A35',marginTop:4},small:{fontSize:12,color:'#65708A'},primary:{backgroundColor:'#651FFF',color:'#FFF',fontWeight:'900',fontSize:15,textAlign:'center',paddingVertical:15,borderRadius:10,marginVertical:5},heading:{fontSize:15,fontWeight:'800',color:'#111A35',marginTop:8},card:{position:'relative',padding:16,borderWidth:1,borderColor:'#E7EAF0',borderRadius:12,backgroundColor:'#FFF'},cardTitle:{fontSize:17,fontWeight:'900',color:'#111A35',marginBottom:6},meta:{fontSize:13,color:'#53617A',marginTop:3},chevron:{position:'absolute',right:14,top:30,fontSize:28,color:'#111A35'},availability:{flexDirection:'row',alignItems:'center',padding:15,borderWidth:1,borderColor:'#E7EAF0',borderRadius:12},green:{color:'#19C763',fontSize:15,marginRight:8},availText:{flex:1,color:'#53617A',fontSize:13},chev:{fontSize:24,color:'#111A35'}});
