import { Link } from 'expo-router';
import { useEffect,useState } from 'react';
import { Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View } from 'react-native';
import { ProfessionalNav } from '../components/ProfessionalNav';
import { authHeaders } from '../lib/session';
import { apiUrl } from '../lib/api';
type Job={id:string;title:string;location?:string;workCity?:string;payCents?:number;companyAverageRating?:number|null;companyRatingCount?:number};
export default function Trabalhos(){const[jobs,setJobs]=useState<Job[]>([]),[message,setMessage]=useState('');useEffect(()=>{void load();},[]);async function load(){const h=await authHeaders();const r=await fetch(apiUrl('/jobs'),{headers:h});if(r.ok)setJobs(await r.json());else setMessage('Entre e complete seu perfil para ver trabalhos.');}async function interest(id:string){const h=await authHeaders();const r=await fetch(apiUrl('/jobs/'+id+'/interest'),{method:'POST',headers:h});setMessage(r.ok?'Interesse enviado':'Não foi possível enviar o interesse');}return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={s.content}><View style={s.headingRow}><View><Text style={s.eyebrow}>OPORTUNIDADES</Text><Text style={s.title}>Trabalhos para você</Text></View><Link href="/copilot" style={s.assistant}>Assistente</Link></View>{jobs.length===0&&!message?<View style={s.emptyCard}><Text style={s.emptyTitle}>Nenhum trabalho disponível agora</Text><Text style={s.meta}>Novas oportunidades aparecerão aqui quando combinarem com seu perfil.</Text></View>:null}{jobs.map(j=><View key={j.id} style={s.card}><View style={s.imagePlaceholder}><Text style={s.imageLabel}>OPORTUNIDADE</Text></View><View style={s.cardBody}><Text style={s.role}>{j.title}</Text><Text style={s.company}>{j.companyRatingCount&&j.companyAverageRating!=null?`Empresa · ${j.companyAverageRating.toFixed(1).replace('.',',')} ★`:'Empresa'}</Text><View style={s.details}><Text style={s.meta}>{j.location??j.workCity??'Local a confirmar'}</Text><Text style={s.pay}>{j.payCents!=null?'R$ '+(j.payCents/100).toFixed(2).replace('.',','):'Valor a confirmar'}</Text></View><Pressable style={s.button} onPress={()=>void interest(j.id)}><Text style={s.action}>QUERO TRABALHAR</Text></Pressable></View></View>)}{message?<Text style={s.message}>{message}</Text>:null}</ScrollView><ProfessionalNav/></SafeAreaView>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#F7F6FB'},content:{padding:20,gap:16,paddingBottom:24},headingRow:{flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between',gap:12},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:.7,color:'#77727F',marginBottom:4},title:{fontSize:28,fontWeight:'800',color:'#20202A'},assistant:{fontSize:15,fontWeight:'800',color:'#5B35D5',paddingBottom:4},card:{overflow:'hidden',borderWidth:1,borderColor:'#E9E6F2',backgroundColor:'#FFFFFF',borderRadius:18},imagePlaceholder:{height:118,backgroundColor:'#EDE9F7',alignItems:'center',justifyContent:'center'},imageLabel:{fontSize:12,fontWeight:'800',letterSpacing:1,color:'#5B35D5'},cardBody:{padding:18,gap:9},role:{fontSize:23,fontWeight:'800',color:'#20202A'},company:{fontSize:14,fontWeight:'700',color:'#5B35D5'},details:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},meta:{fontSize:15,lineHeight:21,color:'#62616B',flexShrink:1},pay:{fontSize:19,fontWeight:'800',color:'#5B35D5'},button:{backgroundColor:'#5B35D5',borderRadius:12,padding:14,marginTop:4},action:{fontSize:16,fontWeight:'800',color:'#FFFFFF',textAlign:'center'},message:{fontSize:15,color:'#62616B'},emptyCard:{padding:20,borderWidth:1,borderColor:'#E9E6F2',backgroundColor:'#FFFFFF',borderRadius:16,gap:7},emptyTitle:{fontSize:18,fontWeight:'800',color:'#20202A'}});
