import { Module } from '@nestjs/common';
import { HealthController } from './health.controller';
import { JobsController } from './jobs.controller';
import { AuthController } from './auth.controller';
import { MeController } from './me.controller';
import { DatabaseService } from './database.service';
import { AuthService } from './auth.service';
import { ProfessionalProfileController } from './professional-profile.controller';
import { WorkAssignmentsController } from './work-assignments.controller';
import { EarningsController } from './earnings.controller';
import { WorkPassportController } from './work-passport.controller';
import { RatingsController } from './ratings.controller';
import { CompanyJobsController } from './company-jobs.controller';
import { CompanyDashboardController } from './company-dashboard.controller';
import { AvailabilityController } from './availability.controller';
import { ReplacementController } from './replacement.controller';
import { TeamsController } from './teams.controller';
import { NotificationsController } from './notifications.controller';
import { ConversationsController } from './conversations.controller';
import { TrustEventsController } from './trust-events.controller';
import { PaymentEventsController } from './payment-events.controller';
import { TalentPoolsController } from './talent-pools.controller';
import { TeamAllocationController } from './team-allocation.controller';
import { PaymentWebhookController } from './payment-webhook.controller';
import { SafetyCasesController } from './safety-cases.controller';
import { SafetyAdminController } from './safety-admin.controller';
import { CompanyJobCreateController } from './company-job-create.controller';
@Module({ controllers: [HealthController, JobsController, AuthController, MeController, ProfessionalProfileController, WorkAssignmentsController, EarningsController, WorkPassportController, RatingsController, CompanyJobsController, CompanyJobCreateController, CompanyDashboardController, AvailabilityController, ReplacementController, TeamsController, NotificationsController, ConversationsController, TrustEventsController, PaymentEventsController, TalentPoolsController, TeamAllocationController, PaymentWebhookController, SafetyCasesController, SafetyAdminController], providers:[DatabaseService,AuthService] })
export class AppModule {}
