import { BadRequestException, Body, Controller, ForbiddenException, Get, Headers, NotFoundException, Param, Post } from '@nestjs/common';
import { AuthService } from './auth.service';
import { DatabaseService } from './database.service';
import { rankCandidates } from './allocation';
import { reliabilityScore } from './reliability-score';
import { confirmationDecision } from './company-confirmation-policy';
import { roleFit } from './role-fit';
import { cityDistanceKm } from './city-proximity';
@Controller('company/jobs')
export class CompanyJobsController {constructor(private readonly db:DatabaseService,private readonly auth:AuthService){}
 private async context(a?:string,tenantId?:string){const identity=await this.auth.identityFromAuthorization(a);if(!tenantId)throw new BadRequestException('tenant_required');const membership=await this.auth.requireMembership(identity.id,tenantId);if(!['owner','admin','manager','company'].includes(membership.role))throw new ForbiddenException('company_role_required');return {identity,tenantId};}
 private async requireJob(db:{query:(sql:string,params?:unknown[])=>Promise<{rows:unknown[]}>},jobId:string){const job=(await db.query('SELECT id,status,title,required_role AS "requiredRole",work_city AS "workCity" FROM company_jobs WHERE id=$1',[jobId])).rows[0] as {id:string;status:string;title:string;requiredRole:string|null;workCity:string|null}|undefined;if(!job)throw new NotFoundException('job_not_found');return job;}
 @Get(':jobId/candidates') async candidates(@Param('jobId') jobId:string,@Headers('authorization') a?:string,@Headers('x-tenant-id') tenantId?:string){const c=await this.context(a,tenantId);return this.db.tenant(c.tenantId,async db=>{await this.requireJob(db,jobId);return (await db.query('SELECT ji.professional_id AS "professionalId",ji.status,p.display_name AS "displayName",p.home_city AS "homeCity",p.primary_role AS "primaryRole" FROM job_interests ji JOIN professional_profiles p ON p.id=ji.professional_id WHERE ji.job_id=$1 ORDER BY ji.created_at',[jobId])).rows;});}
 @Get(':jobId/recommendations') async recommendations(@Param('jobId') jobId:string,@Headers('authorization') a?:string,@Headers('x-tenant-id') tenantId?:string){const c=await this.context(a,tenantId);return this.db.tenant(c.tenantId,async db=>{const job=await this.requireJob(db,jobId);const rows=(await db.query<{professionalId:string;primaryRole:string|null;homeCity:string|null;available:boolean;completed:number;cancelled:number;noShows:number;lateArrivals:number}>('SELECT ji.professional_id AS "professionalId",p.primary_role AS "primaryRole",p.home_city AS "homeCity",EXISTS(SELECT 1 FROM professional_availability pa JOIN company_jobs j ON j.id=ji.job_id WHERE pa.professional_id=ji.professional_id AND pa.starts_at<=j.starts_at AND pa.ends_at>=j.ends_at) AS available,(SELECT count(*)::int FROM work_assignments wa WHERE wa.professional_id=ji.professional_id AND wa.status=\'completed\') completed,(SELECT count(*)::int FROM work_assignments wa WHERE wa.professional_id=ji.professional_id AND wa.status=\'cancelled\') cancelled,(SELECT count(*)::int FROM trust_events te WHERE te.professional_id=ji.professional_id AND te.event_type=\'no_show\') AS "noShows",(SELECT count(*)::int FROM trust_events te WHERE te.professional_id=ji.professional_id AND te.event_type=\'late_arrival\') AS "lateArrivals" FROM job_interests ji JOIN professional_profiles p ON p.id=ji.professional_id WHERE ji.job_id=$1',[jobId])).rows;return rankCandidates(rows.map(x=>{const r=reliabilityScore({completed:x.completed,cancelled:x.cancelled,noShows:x.noShows,lateArrivals:x.lateArrivals});const distanceKm=cityDistanceKm(job.workCity,x.homeCity);return {professionalId:x.professionalId,match:{availability:x.available,roleFit:roleFit(job.requiredRole??job.title,x.primaryRole),reliability:r.score/100,...(distanceKm==null?{}:{distanceKm})}};}));});}
 @Post(':jobId/confirm') async confirm(@Param('jobId') jobId:string,@Body() body:{professionalId?:string},@Headers('authorization') a?:string,@Headers('x-tenant-id') tenantId?:string){if(!body.professionalId)throw new BadRequestException('professional_required');const c=await this.context(a,tenantId);return this.db.tenant(c.tenantId,async db=>{const job=await this.requireJob(db,jobId);if(job.status!=='open')throw new BadRequestException('job_not_open');const interest=(await db.query('SELECT 1 FROM job_interests WHERE job_id=$1 AND professional_id=$2',[jobId,body.professionalId])).rows[0];if(!interest)throw new BadRequestException('job_interest_required');const existing=(await db.query<{id:string;jobId:string;professionalId:string;status:string;confirmedAt:string}>('SELECT id,job_id AS "jobId",professional_id AS "professionalId",status,confirmed_at AS "confirmedAt" FROM work_assignments WHERE job_id=$1 AND professional_id=$2',[jobId,body.professionalId])).rows[0];const decision=confirmationDecision(existing?.status);if(decision==='conflict')throw new BadRequestException('assignment_state_conflict');if(decision==='return_existing')return existing;const r=await db.query('INSERT INTO work_assignments(tenant_id,job_id,professional_id,status) VALUES($1,$2,$3,$4) RETURNING id,job_id AS "jobId",professional_id AS "professionalId",status,confirmed_at AS "confirmedAt"',[c.tenantId,jobId,body.professionalId,'confirmed']);await db.query('UPDATE job_interests SET status=$1 WHERE job_id=$2 AND professional_id=$3',['confirmed',jobId,body.professionalId]);const recipient=(await db.query<{identityId:string}>('SELECT identity_id AS "identityId" FROM professional_profiles WHERE id=$1',[body.professionalId])).rows[0];if(recipient?.identityId)await db.query("INSERT INTO notifications(tenant_id,identity_id,type,title,body) VALUES($1,$2,'assignment_confirmed','Trabalho confirmado','A empresa confirmou você para um trabalho. Veja os detalhes na sua agenda.')",[c.tenantId,recipient.identityId]);return r.rows[0];});}}
