import { BadRequestException, Body, Controller, Get, Headers, Post } from '@nestjs/common';
import { AuthService } from './auth.service';
import { DatabaseService } from './database.service';
@Controller('company/jobs')
export class CompanyJobCreateController {
 constructor(private readonly db:DatabaseService,private readonly auth:AuthService){}
 private async context(a?:string,tenantId?:string){const identity=await this.auth.identityFromAuthorization(a);if(!tenantId)throw new BadRequestException('tenant_required');const membership=await this.auth.requireMembership(identity.id,tenantId);if(!['owner','admin','manager','company'].includes(membership.role))throw new BadRequestException('company_role_required');return {identity,tenantId};}
 @Get() async list(@Headers('authorization') a?:string,@Headers('x-tenant-id') tenantId?:string){const c=await this.context(a,tenantId);return this.db.tenant(c.tenantId,async db=>(await db.query('SELECT id,title,status,location,work_city AS "workCity",starts_at AS "startsAt",ends_at AS "endsAt",pay_cents AS "payCents" FROM company_jobs WHERE tenant_id=$1 ORDER BY created_at DESC',[c.tenantId])).rows);}
 @Post() async create(@Body() body:{title?:string;requiredRole?:string;location?:string;workCity?:string;startsAt?:string;endsAt?:string;payCents?:number},@Headers('authorization') a?:string,@Headers('x-tenant-id') tenantId?:string){const c=await this.context(a,tenantId);if(!body.title?.trim())throw new BadRequestException('title_required');if(body.payCents!=null&&(!Number.isInteger(body.payCents)||body.payCents<0))throw new BadRequestException('pay_invalid');const title=body.title.trim(),requiredRole=body.requiredRole?.trim()||title;return this.db.tenant(c.tenantId,async db=>(await db.query('INSERT INTO company_jobs(tenant_id,title,required_role,status,location,work_city,starts_at,ends_at,pay_cents) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,title,required_role AS "requiredRole",status,location,work_city AS "workCity",starts_at AS "startsAt",ends_at AS "endsAt",pay_cents AS "payCents"',[c.tenantId,title,requiredRole,'open',body.location?.trim()||null,body.workCity?.trim()||null,body.startsAt||null,body.endsAt||null,body.payCents??0])).rows[0]);}
}
