import { Controller, Get, Headers, NotFoundException, Param, Post } from '@nestjs/common';
import { AuthService } from './auth.service';
import { DatabaseService } from './database.service';
@Controller('jobs')
export class JobsController {
 constructor(private readonly db:DatabaseService,private readonly auth:AuthService){}
 private identity(authorization?:string){return this.auth.identityFromAuthorization(authorization);}
 @Get() async list(@Headers('authorization') authorization?:string){await this.identity(authorization);return (await this.db.query('SELECT job_id AS id,title,status,location,work_city AS "workCity",required_role AS "requiredRole",starts_at AS "startsAt",ends_at AS "endsAt",pay_cents AS "payCents" FROM marketplace_jobs WHERE status=$1 ORDER BY starts_at NULLS LAST,updated_at DESC',['open'])).rows;}
 @Post(':jobId/interest') async expressInterest(@Param('jobId') jobId:string,@Headers('authorization') authorization?:string){const identity=await this.identity(authorization);const p=await this.db.query<{id:string}>('SELECT id FROM professional_profiles WHERE identity_id=$1',[identity.id]);const professional=p.rows[0];if(!professional)throw new NotFoundException('professional_profile_required');const j=await this.db.query<{job_id:string}>('SELECT job_id FROM marketplace_jobs WHERE job_id=$1 AND status=$2',[jobId,'open']);if(!j.rows[0])throw new NotFoundException('job_not_found');const r=await this.db.query('INSERT INTO marketplace_interests(job_id,professional_id,status) VALUES($1,$2,$3) ON CONFLICT(job_id,professional_id) DO UPDATE SET status=CASE WHEN marketplace_interests.status=$4 THEN marketplace_interests.status ELSE EXCLUDED.status END,updated_at=now() RETURNING job_id AS "jobId",professional_id AS "professionalId",status',[jobId,professional.id,'interested','confirmed']);return r.rows[0];}
 @Get(':jobId/interest') async getInterest(@Param('jobId') jobId:string,@Headers('authorization') authorization?:string){const identity=await this.identity(authorization);const r=await this.db.query('SELECT mi.job_id AS "jobId",mi.professional_id AS "professionalId",mi.status FROM marketplace_interests mi JOIN professional_profiles p ON p.id=mi.professional_id WHERE mi.job_id=$1 AND p.identity_id=$2',[jobId,identity.id]);return r.rows[0]??null;}
}
