import { BadRequestException, ForbiddenException, Body, Controller, Get, Headers, Param, Post } from '@nestjs/common';
import type { PoolClient } from 'pg';
import { AuthService } from './auth.service';
import { DatabaseService } from './database.service';
import { rankCandidates } from './allocation';
import { reliabilityScore } from './reliability-score';
import { roleFit } from './role-fit';
import { cityDistanceKm } from './city-proximity';

@Controller('company/replacements')
export class ReplacementController {
 constructor(private readonly db:DatabaseService,private readonly auth:AuthService){}

 private async ctx(a?:string,t?:string){const i=await this.auth.identityFromAuthorization(a);if(!t)throw new BadRequestException('tenant_required');const m=await this.auth.requireMembership(i.id,t);if(!['owner','admin','manager','company'].includes(m.role))throw new ForbiddenException('company_role_required');return t;}

 private async ranked(db:PoolClient,replacementId:string,tenant:string,openOnly=false){
  const rr=(await db.query<{assignmentId:string;jobId:string;originalProfessionalId:string;title:string;requiredRole:string|null;workCity:string|null;startsAt:string|null;endsAt:string|null}>(`SELECT rr.assignment_id AS "assignmentId",wa.job_id AS "jobId",wa.professional_id AS "originalProfessionalId",j.title,j.required_role AS "requiredRole",j.work_city AS "workCity",j.starts_at AS "startsAt",j.ends_at AS "endsAt" FROM replacement_requests rr JOIN work_assignments wa ON wa.id=rr.assignment_id AND wa.tenant_id=rr.tenant_id JOIN company_jobs j ON j.id=wa.job_id AND j.tenant_id=rr.tenant_id WHERE rr.id=$1 AND rr.tenant_id=$2${openOnly?" AND rr.status='open'":''}`,[replacementId,tenant])).rows[0];
  if(!rr)throw new BadRequestException(openOnly?'replacement_not_open':'replacement_not_found');
  const rows=(await db.query<{professionalId:string;displayName:string;primaryRole:string|null;homeCity:string|null;available:boolean;completed:number;cancelled:number;noShows:number;lateArrivals:number}>(`SELECT DISTINCT tpm.professional_id AS "professionalId",p.display_name AS "displayName",p.primary_role AS "primaryRole",p.home_city AS "homeCity",EXISTS(SELECT 1 FROM professional_availability_network pa WHERE pa.professional_id=tpm.professional_id AND pa.starts_at<=$3::timestamptz AND pa.ends_at>=$4::timestamptz) AS available,(SELECT count(*)::int FROM work_assignments wa2 WHERE wa2.tenant_id=$1 AND wa2.professional_id=tpm.professional_id AND wa2.status='completed') completed,(SELECT count(*)::int FROM work_assignments wa2 WHERE wa2.tenant_id=$1 AND wa2.professional_id=tpm.professional_id AND wa2.status='cancelled') cancelled,(SELECT count(*)::int FROM trust_events te WHERE te.tenant_id=$1 AND te.professional_id=tpm.professional_id AND te.event_type='no_show') AS "noShows",(SELECT count(*)::int FROM trust_events te WHERE te.tenant_id=$1 AND te.professional_id=tpm.professional_id AND te.event_type='late_arrival') AS "lateArrivals" FROM talent_pool_members tpm JOIN professional_profiles p ON p.id=tpm.professional_id WHERE tpm.tenant_id=$1 AND tpm.professional_id<>$2`,[tenant,rr.originalProfessionalId,rr.startsAt,rr.endsAt])).rows;
  const ranked=rankCandidates(rows.map(x=>{const reliability=reliabilityScore({completed:x.completed,cancelled:x.cancelled,noShows:x.noShows,lateArrivals:x.lateArrivals});const distanceKm=cityDistanceKm(rr.workCity,x.homeCity);return {professionalId:x.professionalId,match:{availability:x.available,roleFit:roleFit(rr.requiredRole??rr.title,x.primaryRole),reliability:reliability.score/100,...(distanceKm==null?{}:{distanceKm})}};}));
  return ranked.map(item=>({...item,displayName:rows.find(x=>x.professionalId===item.professionalId)?.displayName??'Profissional'}));
 }

 @Get() async list(@Headers('authorization')a?:string,@Headers('x-tenant-id')t?:string){const tenant=await this.ctx(a,t);return this.db.tenant(tenant,async db=>(await db.query('SELECT id,assignment_id AS "assignmentId",status,replacement_professional_id AS "replacementProfessionalId",reason,created_at AS "createdAt" FROM replacement_requests WHERE tenant_id=$1 ORDER BY created_at DESC',[tenant])).rows);}

 @Get(':id/candidates') async candidates(@Param('id')id:string,@Headers('authorization')a?:string,@Headers('x-tenant-id')t?:string){const tenant=await this.ctx(a,t);return this.db.tenant(tenant,db=>this.ranked(db,id,tenant));}

 @Post(':id/auto-match') async autoMatch(@Param('id')id:string,@Headers('authorization')a?:string,@Headers('x-tenant-id')t?:string){const tenant=await this.ctx(a,t);return this.db.tenant(tenant,async db=>{const ranked=await this.ranked(db,id,tenant,true);const best=ranked[0];if(!best)throw new BadRequestException('no_replacement_available');return {replacementRequestId:id,recommendedProfessionalId:best.professionalId,recommendedProfessionalName:best.displayName,score:best.score,reasons:best.reasons};});}

 @Post(':id/select') async select(@Param('id')id:string,@Body()body:{professionalId?:string},@Headers('authorization')a?:string,@Headers('x-tenant-id')t?:string){const tenant=await this.ctx(a,t);if(!body.professionalId)throw new BadRequestException('professional_required');return this.db.tenant(tenant,async db=>{const rr=(await db.query<{assignmentId:string}>('SELECT assignment_id AS "assignmentId" FROM replacement_requests WHERE id=$1 AND tenant_id=$2 AND status=\'open\'',[id,tenant])).rows[0];if(!rr)throw new BadRequestException('replacement_not_open');const original=(await db.query<{jobId:string;status:string}>('SELECT job_id AS "jobId",status FROM work_assignments WHERE id=$1 AND tenant_id=$2',[rr.assignmentId,tenant])).rows[0];if(!original)throw new BadRequestException('assignment_not_found');if(!['confirmed','checked_in','in_progress'].includes(original.status))throw new BadRequestException('assignment_not_replaceable');const member=(await db.query('SELECT 1 FROM talent_pool_members WHERE tenant_id=$1 AND professional_id=$2',[tenant,body.professionalId])).rows[0];if(!member)throw new BadRequestException('replacement_candidate_required');const available=(await db.query('SELECT 1 FROM professional_availability_network pa JOIN company_jobs j ON j.id=$2 AND j.tenant_id=$3 WHERE pa.professional_id=$1 AND pa.starts_at<=j.starts_at AND pa.ends_at>=j.ends_at LIMIT 1',[body.professionalId,original.jobId,tenant])).rows[0];if(!available)throw new BadRequestException('replacement_candidate_unavailable');const a2=(await db.query<{id:string}>("INSERT INTO work_assignments(tenant_id,job_id,professional_id,status) VALUES($1,$2,$3,'confirmed') ON CONFLICT(job_id,professional_id) DO UPDATE SET status=work_assignments.status RETURNING id",[tenant,original.jobId,body.professionalId])).rows[0];if(!a2)throw new BadRequestException('replacement_assignment_failed');await db.query("UPDATE work_assignments SET status='cancelled' WHERE id=$1 AND tenant_id=$2",[rr.assignmentId,tenant]);await db.query("UPDATE replacement_requests SET status='matched',replacement_professional_id=$2,resolved_at=now() WHERE id=$1 AND tenant_id=$3",[id,body.professionalId,tenant]);const recipient=(await db.query<{identityId:string}>('SELECT identity_id AS "identityId" FROM professional_profiles WHERE id=$1',[body.professionalId])).rows[0];if(recipient?.identityId)await db.query("INSERT INTO notifications(tenant_id,identity_id,type,title,body) VALUES($1,$2,'replacement_confirmed','Substituição confirmada','Você foi confirmado como substituto para um trabalho. Veja sua agenda.')",[tenant,recipient.identityId]);return {replacementRequestId:id,assignmentId:a2.id,replacedAssignmentId:rr.assignmentId,professionalId:body.professionalId,status:'matched'};});}

 @Post(':assignmentId') async create(@Param('assignmentId')assignmentId:string,@Body()body:{reason?:string},@Headers('authorization')a?:string,@Headers('x-tenant-id')t?:string){const tenant=await this.ctx(a,t);return this.db.tenant(tenant,async db=>{const assignment=(await db.query<{status:string}>('SELECT status FROM work_assignments WHERE id=$1 AND tenant_id=$2',[assignmentId,tenant])).rows[0];if(!assignment)throw new BadRequestException('assignment_not_found');if(!['confirmed','checked_in','in_progress'].includes(assignment.status))throw new BadRequestException('assignment_not_replaceable');return (await db.query(`INSERT INTO replacement_requests(tenant_id,assignment_id,status,reason) VALUES($1,$2,'open',$3) ON CONFLICT(assignment_id,status) DO UPDATE SET reason=EXCLUDED.reason RETURNING id,assignment_id AS "assignmentId",status,reason`,[tenant,assignmentId,body.reason?.trim()||null])).rows[0];});}
}
