import { BadRequestException, Body, Controller, Get, Headers, NotFoundException, Param, Post } from '@nestjs/common';
import { AuthService } from './auth.service';
import { DatabaseService } from './database.service';
import { allowedPreviousStates, AssignmentNextState } from './assignment-lifecycle';
@Controller('assignments')
export class WorkAssignmentsController {
 constructor(private readonly db:DatabaseService,private readonly auth:AuthService){}
 private async context(authorization?:string,tenantId?:string){const identity=await this.auth.identityFromAuthorization(authorization);if(!tenantId)throw new BadRequestException('tenant_required');await this.auth.requireMembership(identity.id,tenantId);return {identity,tenantId};}
 @Get('mine') async mine(@Headers('authorization') authorization?:string,@Headers('x-tenant-id') tenantId?:string){const identity=await this.auth.identityFromAuthorization(authorization);const tenantIds=tenantId?[tenantId]:(await this.auth.memberships(identity.id)).filter(m=>m.role==='professional').map(m=>m.tenant_id);if(tenantId)await this.auth.requireMembership(identity.id,tenantId);const all:any[]=[];for(const t of tenantIds){const rows=await this.db.tenant(t,async db=>(await db.query('SELECT wa.id,wa.status,wa.confirmed_at AS "confirmedAt",wa.checked_in_at AS "checkedInAt",wa.checked_out_at AS "checkedOutAt",wa.completed_at AS "completedAt",j.id AS "jobId",j.title,j.location,j.starts_at AS "startsAt",j.ends_at AS "endsAt",j.pay_cents AS "payCents" FROM work_assignments wa JOIN professional_profiles p ON p.id=wa.professional_id JOIN company_jobs j ON j.id=wa.job_id WHERE p.identity_id=$1 ORDER BY j.starts_at NULLS LAST',[identity.id])).rows);all.push(...rows.map((r:any)=>({...r,tenantId:t})));}return all.sort((a,b)=>String(a.startsAt??'9999').localeCompare(String(b.startsAt??'9999')));}
 private async transition(id:string,next:AssignmentNextState,authorization?:string,tenantId?:string,coords?:{lat?:number;lng?:number}){const c=await this.context(authorization,tenantId);return this.db.tenant(c.tenantId,async db=>{const p=await db.query<{id:string}>('SELECT id FROM professional_profiles WHERE identity_id=$1',[c.identity.id]);if(!p.rows[0])throw new NotFoundException('professional_profile_required');const stamp=next==='checked_in'?'checked_in_at':next==='checked_out'?'checked_out_at':next==='completed'?'completed_at':null;const stampSql=stamp?','+stamp+'=now()':'';const hasLat=coords?.lat!=null,hasLng=coords?.lng!=null;if(hasLat!==hasLng)throw new BadRequestException('location_pair_required');const lat=hasLat?Number(coords!.lat):null,lng=hasLng?Number(coords!.lng):null;if(lat!==null&&(!Number.isFinite(lat)||lat < -90||lat > 90))throw new BadRequestException('latitude_invalid');if(lng!==null&&(!Number.isFinite(lng)||lng < -180||lng > 180))throw new BadRequestException('longitude_invalid');const geo=lat!==null&&lng!==null?(next==='checked_in'?',check_in_lat=$5,check_in_lng=$6':next==='checked_out'?',check_out_lat=$5,check_out_lng=$6':''):'';const params:any[]=[next,id,p.rows[0].id,allowedPreviousStates(next)];if(geo)params.push(lat,lng);const r=await db.query('UPDATE work_assignments SET status=$1'+stampSql+geo+' WHERE id=$2 AND professional_id=$3 AND status=ANY($4::text[]) RETURNING id,status,confirmed_at AS "confirmedAt",checked_in_at AS "checkedInAt",checked_out_at AS "checkedOutAt",completed_at AS "completedAt"',params);if(!r.rows[0])throw new BadRequestException('invalid_assignment_transition');if(next==='completed'){await db.query('INSERT INTO earnings_ledger(tenant_id,assignment_id,professional_id,amount_cents,status) SELECT wa.tenant_id,wa.id,wa.professional_id,COALESCE(j.pay_cents,0),$2 FROM work_assignments wa JOIN company_jobs j ON j.id=wa.job_id WHERE wa.id=$1 ON CONFLICT(assignment_id) DO NOTHING',[id,'payable']);}return r.rows[0];});}
 @Post(':id/check-in') checkIn(@Param('id') id:string,@Body() body:{lat?:number;lng?:number},@Headers('authorization') a?:string,@Headers('x-tenant-id') t?:string){return this.transition(id,'checked_in',a,t,body);}
 @Post(':id/start') start(@Param('id') id:string,@Headers('authorization') a?:string,@Headers('x-tenant-id') t?:string){return this.transition(id,'in_progress',a,t);}
 @Post(':id/check-out') checkOut(@Param('id') id:string,@Body() body:{lat?:number;lng?:number},@Headers('authorization') a?:string,@Headers('x-tenant-id') t?:string){return this.transition(id,'checked_out',a,t,body);}
 @Post(':id/complete') complete(@Param('id') id:string,@Headers('authorization') a?:string,@Headers('x-tenant-id') t?:string){return this.transition(id,'completed',a,t);}
}
