import { BadRequestException, Controller, Get, Headers, NotFoundException, Param, Post } from '@nestjs/common';
import { AuthService } from './auth.service';
import { DatabaseService } from './database.service';
@Controller('assignments')
export class WorkAssignmentsController {
 constructor(private readonly db:DatabaseService,private readonly auth:AuthService){}
 private async context(authorization?:string,tenantId?:string){const identity=await this.auth.identityFromAuthorization(authorization);if(!tenantId)throw new BadRequestException('tenant_required');await this.auth.requireMembership(identity.id,tenantId);return {identity,tenantId};}
 @Get('mine') async mine(@Headers('authorization') authorization?:string,@Headers('x-tenant-id') tenantId?:string){const c=await this.context(authorization,tenantId);return this.db.tenant(c.tenantId,async db=>(await db.query('SELECT wa.id,wa.status,wa.confirmed_at AS "confirmedAt",wa.checked_in_at AS "checkedInAt",wa.checked_out_at AS "checkedOutAt",wa.completed_at AS "completedAt",j.id AS "jobId",j.title,j.location,j.starts_at AS "startsAt",j.ends_at AS "endsAt",j.pay_cents AS "payCents" FROM work_assignments wa JOIN professional_profiles p ON p.id=wa.professional_id JOIN company_jobs j ON j.id=wa.job_id WHERE p.identity_id=$1 ORDER BY j.starts_at NULLS LAST',[c.identity.id])).rows);}
 private async transition(id:string,next:string,allowed:string[],authorization?:string,tenantId?:string){const c=await this.context(authorization,tenantId);return this.db.tenant(c.tenantId,async db=>{const p=await db.query<{id:string}>('SELECT id FROM professional_profiles WHERE identity_id=$1',[c.identity.id]);if(!p.rows[0])throw new NotFoundException('professional_profile_required');const stamp=next==='checked_in'?'checked_in_at':next==='checked_out'?'checked_out_at':next==='completed'?'completed_at':null;const stampSql=stamp?','+stamp+'=now()':'';const r=await db.query('UPDATE work_assignments SET status=$1'+stampSql+' WHERE id=$2 AND professional_id=$3 AND status=ANY($4::text[]) RETURNING id,status,confirmed_at AS "confirmedAt",checked_in_at AS "checkedInAt",checked_out_at AS "checkedOutAt",completed_at AS "completedAt"',[next,id,p.rows[0].id,allowed]);if(!r.rows[0])throw new BadRequestException('invalid_assignment_transition');if(next==='completed'){await db.query('INSERT INTO earnings_ledger(tenant_id,assignment_id,professional_id,amount_cents,status) SELECT wa.tenant_id,wa.id,wa.professional_id,COALESCE(j.pay_cents,0),$2 FROM work_assignments wa JOIN company_jobs j ON j.id=wa.job_id WHERE wa.id=$1 ON CONFLICT(assignment_id) DO NOTHING',[id,'payable']);}return r.rows[0];});}
 @Post(':id/check-in') checkIn(@Param('id') id:string,@Headers('authorization') a?:string,@Headers('x-tenant-id') t?:string){return this.transition(id,'checked_in',['confirmed'],a,t);}
 @Post(':id/start') start(@Param('id') id:string,@Headers('authorization') a?:string,@Headers('x-tenant-id') t?:string){return this.transition(id,'in_progress',['checked_in'],a,t);}
 @Post(':id/check-out') checkOut(@Param('id') id:string,@Headers('authorization') a?:string,@Headers('x-tenant-id') t?:string){return this.transition(id,'checked_out',['checked_in','in_progress'],a,t);}
 @Post(':id/complete') complete(@Param('id') id:string,@Headers('authorization') a?:string,@Headers('x-tenant-id') t?:string){return this.transition(id,'completed',['checked_out'],a,t);}
}
