import test from 'node:test';import assert from 'node:assert/strict';
import {createSessionQueue,persistVerifiedSession} from '../lib/session-transaction.ts';
const fixture=()=>{let state={token:'old',tenantId:'old-company'};return {read:async()=>({...state}),write:async next=>{state={...next}}};};
test('verified persistence records both token and tenant before declaring success',async()=>{const a=fixture();assert.equal(await persistVerifiedSession(a,{token:'new',tenantId:'new-company'},'old',()=>true),'saved');assert.deepEqual(await a.read(),{token:'new',tenantId:'new-company'});});
test('professional signin clears old company context only as part of the verified session',async()=>{const a=fixture();assert.equal(await persistVerifiedSession(a,{token:'pro',tenantId:null},'old',()=>true),'saved');assert.deepEqual(await a.read(),{token:'pro',tenantId:null});});
test('changed session or blurred operation never starts its storage update',async()=>{const a=fixture();for(const [expected,current] of [['another',true],['old',false]])assert.equal(await persistVerifiedSession(a,{token:'new',tenantId:null},expected,()=>current),'stale');assert.deepEqual(await a.read(),{token:'old',tenantId:'old-company'});});
test('partial failed storage restores the old pair and cannot claim saved',async()=>{const a=fixture(),write=a.write;let once=true;a.write=async state=>{if(once){once=false;await write({token:state.token,tenantId:null});return;}await write(state)};assert.equal(await persistVerifiedSession(a,{token:'new',tenantId:'company'},'old',()=>true),'failed');assert.deepEqual(await a.read(),{token:'old',tenantId:'old-company'});});
test('serialized readers never observe a partially written pair; stale rollback precedes a later login',async()=>{const queue=createSessionQueue(),a=fixture(),write=a.write;let release;const gate=new Promise(resolve=>{release=resolve});let current=true;a.write=async state=>{if(state.token==='first'){await write({token:'first',tenantId:null});await gate;}await write(state)};const first=queue.run(()=>persistVerifiedSession(a,{token:'first',tenantId:'company'},'old',()=>current));await new Promise(resolve=>setImmediate(resolve));const read=queue.run(a.read),second=queue.run(()=>persistVerifiedSession(a,{token:'second',tenantId:'second-company'},'old',()=>true));current=false;release();assert.equal(await first,'stale');assert.deepEqual(await read,{token:'old',tenantId:'old-company'});assert.equal(await second,'saved');assert.deepEqual(await a.read(),{token:'second',tenantId:'second-company'});});
test('a rejected queued operation does not poison future session reads or writes',async()=>{const q=createSessionQueue();await assert.rejects(q.run(async()=>{throw Error('storage')}));assert.equal(await q.run(async()=>42),42);});

test('a thrown storage write restores the previous pair and never reports successful login',async()=>{const a=fixture(),write=a.write;let once=true;a.write=async state=>{if(once){once=false;await write({token:state.token,tenantId:null});throw Error('SecureStore failure');}await write(state)};assert.equal(await persistVerifiedSession(a,{token:'new',tenantId:'new-company'},'old',()=>true),'failed');assert.deepEqual(await a.read(),{token:'old',tenantId:'old-company'});});
